### ISSUE TITLE
Any way to use this with a live audio stream? 

### ISSUE THREAD

**Issue by thisissami** [eXifreXi/eXiSoundVis#10]
I'm starting to design & develop a world in Unreal that I want to react to audio streams. I'm curious if it would be relatively straightforward to repurpose this library to do just that, or if the architecture makes it solely possible to do this with files that are read ahead of time? I would imagine that a decompressed OGG file isn't very different from an audio stream, but I'm not 100% sure. 

Thanks for taking the time to read this!

**Comment by Tsarpf** [comment]
That is pretty much what I did here: https://github.com/Tsarpf/UE4-Procedural-Audio / https://rabid.prototyping.xyz/2017/01/05/procedural-mesh-generation-from-live-audio-in-unreal-engine-4/ (also see https://rabid.prototyping.xyz/2015/12/29/programmatically-capture-whats-playing-on-windows/). You could get the audio from a microphone as well.

And yes, "decompressed OGG" is just PCM (see f.ex https://en.wikipedia.org/wiki/Pulse-code_modulation), as is any other type of audio file when it's opened for playing, or as in this case, for getting the frequency spectrum out of it.

The PCM stream can have slightly different representations though, for example, it could have "queued" the two (if stereo) channel's samples in a different order, and the samples themselves can be for example 16 bit integers with values ranging from 0 to 2^16 or floats where the values range from -1 to 1.

But in the end they are all convertable to work with this plugin's frequency spectrum calculator.

Feel free to ask if you need more help.

**Comment by thisissami** [comment]
Thanks so much for the response @Tsarpf! That's really useful. :) I'm trying to capture multiple audio streams via an audio interface to visualize different things simultaneously, and your posts will be quite useful in that endeavour!!

I've chosen to build a prototype for the project I'm working on in TouchDesigner first, and then once I've finalized the design, to code it up in Unreal. Your writing will be really handy then, so I'm definitely bookmarking this stuff. :) 

> This post is written as a kind of information dump I would have wanted to read when I started figuring this all out.

 ^I'm really happy that you have done this! :D Makes my life significantly easier :D
