### ISSUE TITLE
4.12 update not working 

### ISSUE THREAD

**Issue by twitchplayskh** [eXifreXi/eXiSoundVis#6]
i love this plugin and i whent to go test the 4.12 test map the udk i run tells me this 
http://imgur.com/a/DMrZO all i have that i can dl is  4.12.1 what did i f**k up

**Comment by eXifreXi** [comment]
Hey there,

I will recompile it for 4.12.1 in a few minutes.

Cheers.

**Comment by twitchplayskh** [comment]
cool

**Comment by eXifreXi** [comment]
Should be updated now.

**Comment by twitchplayskh** [comment]
did you update the test map as well

**Comment by eXifreXi** [comment]
Yes.

**Comment by twitchplayskh** [comment]
ok cool thank you

**Comment by eXifreXi** [comment]
Would be nice if you could try it out and tell me here if it's working. Then I can close the issue.

**Comment by twitchplayskh** [comment]
will do

**Comment by twitchplayskh** [comment]
it works you can close the issue amazing support from the devs gg

**Comment by eXifreXi** [comment]
Glad it works.

Cheers!
